#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.107.152.161:3306/dev
#    username: dev
#    password: nHH29kEA7!
mybatis:
  config-location: mybatis-config.xml